POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlllZXQiLCJpZCI6MSwiaWF0IjoxNjcxNjA5ODAxfQ.PFev44RzbM96rstZkYRtr8YQ0v-XkxrzCz0PGkkrz1E

{
    "title": "Mmmmm",
    "author": "Aaaaaaaaaaa",
    "url": "https://www.ccccccccc.com/",
    "likes": 10
}